/* eslint-disable prettier/prettier */
// taskActionTypes.js
export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

// get All task
export const GET_ALL_TASKS_REQUEST = 'GET_ALL_TASKS_REQUEST';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const GET_ALL_TASKS_FAILURE = 'GET_ALL_TASKS_FAILURE';


// COMPLETED TASK
export const GET_COMPLETED_TASKS_SUCCESS = 'GET_COMPLETED_TASKS_SUCCESS';

// Todays Task
export const GET_TODAYS_TASKS_SUCCESS="GET_TODAYS_TASKS_SUCCESS";

// delete task
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

// update task status
export const UPDATE_TASK_STATUS_REQUEST = 'UPDATE_TASK_STATUS_REQUEST';
export const UPDATE_TASK_STATUS_SUCCESS = 'UPDATE_TASK_STATUS_SUCCESS';
export const UPDATE_TASK_STATUS_FAILURE = 'UPDATE_TASK_STATUS_FAILURE';